import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NavBar, MaybeShowNavbar } from "@/components/home";
import { AuthProvider } from "@/components/context/authContext"; // Import your AuthProvider
import { Toaster } from "sonner";

const inter = Inter({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`relative ${inter.className}`}>
        <Toaster
          richColors
          position="top-right"
          toastOptions={{ duration: 1000, closeButton: true }}
        />
        <AuthProvider>
          <MaybeShowNavbar>
            <NavBar />
          </MaybeShowNavbar>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
